# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'PlayerFMY' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for PlayerFMY

pod 'Masonry'


  target 'PlayerFMYTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'PlayerFMYUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
