# Uncomment the next line to define a global platform for your project
platform :ios, '8.0'

target 'DQUIViewlib' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for DQUIViewlib

pod 'Masonry'
pod 'LKDBHelper'
pod 'JSONModel'
pod 'SDWebImage', '~> 4.4.2'
pod 'AFNetwork'
#pod 'JTMaterialSwitch'
pod 'Bytedance-UnionAD'

  target 'DQUIViewlibTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'DQUIViewlibUITests' do
    inherit! :search_paths
    # Pods for testing
  end
  
  target 'ServiceEXT' do
      inherit! :search_paths
  end

end
