# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'DQUIViewlib' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for DQUIViewlib

pod 'Masonry'


  target 'DQUIViewlibTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'DQUIViewlibUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
