# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'gcd' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for gcd

   pod 'YYDispatchQueuePool', '~> 1.0'


  target 'gcdTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'gcdUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
